/* eslint-disable max-len */
// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  userName: '',
  passWord: '',
  appInfo: null,
  userProfile: null,
  endPoint: 'https://cloud-549579568.onetsolutions.network/nabysyrhrs/',
  //endPoint:'https://technoweb.homeip.net/nabysyrhrs/',
  //endPoint: 'https://groupe-pam.net/nabysyrhrs/',
  employeConnecte: null,
  tokenUser:''
  //tokenUser: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYW1fYXBwbGljYXRpb24iOiJbTkFieVN5IFJIIC0gUlNdIiwicGFtX2NsaWVudCI6Ii1QQVVMIEVUIEFJQ0hBIE1BQ0hJTkVSSUUtIiwiY2xpZW50X2FkciI6IlphY2sgTWJhbyBEQUtBUlwvU0VORUdBTCIsImNsaWVudF90ZWwiOiJUZWw6ICsyMjEgMzMgODM2IDE0IDc3IiwiYm91dGlxdWVfaWQiOjAsInVzZXJfaWQiOjMsInVzZXJfbG9naW4iOiJ0aGllcm5vIiwidXNlcl9kYXRhIjoie1wiSURcIjpcIjNcIixcIk5PTVwiOlwiVEhJRVJOT1wiLFwiUFJFTk9NXCI6XCJBQkRPVUxBWUVcIixcIkFEUkVTU0VcIjpcIlwiLFwiVEVMXCI6XCJcIixcIkxPR0lOXCI6XCJ0aGllcm5vXCIsXCJQQVNTV09SRFwiOlwiODFkYzliZGI1MmQwNGRjMjAwMzZkYmQ4MzEzZWQwNTVcIixcIkRBVEVFTlRSRUVcIjpcIlwiLFwiREFURUNSRUFUSU9OXCI6XCJcIixcIkhFVVJFQ1JFQVRJT05cIjpcIlwiLFwiTklWRUFVQUNDRVNcIjpcIjRcIixcIlBST0ZJTEVcIjpcIkZJTkFOQ0lFUlwiLFwiQkxPUVVFXCI6XCJOT05cIixcIkxvY2FsTG9naW5Db2RlXCI6XCIwXCIsXCJDSEFOR0VEQVRFXCI6XCIwXCIsXCJDSEFOR0VGQUNUVVJFXCI6XCIwXCIsXCJDSEFOR0VUT1RBTEJPTlwiOlwiMFwiLFwiU0hPV0lOVkVOVEFJVEVfQVZcIjpcIjBcIixcIlNIT1dGQUNUVVJFXCI6XCIwXCIsXCJVUERBVEVQQVNTV09SRFwiOlwiMFwiLFwiVVBEQVRFU1RPQ0tcIjpcIjBcIixcIkNIQU5HRUxJVlJBSVNPTkRBVEVcIjpcIjBcIixcIkVUQVRcIjpcIkFjdGlmXCIsXCJTSE9XQ0FJU1NFXCI6XCIwXCIsXCJTSE9XTUFHQVpJTlwiOlwiMFwiLFwiT25seUxpbWl0ZUZhY3RUb0RheVwiOlwiMFwiLFwiU2hvd1N0b2NrVmVudGVcIjpcIjBcIixcIlNIT1dNYWdhc2luXCI6XCIwXCIsXCJDQU5fUkVUT1VSX1ZFTlRFXCI6XCIxXCIsXCJDQU5fUkVUT1VSX0JMXCI6XCIxXCIsXCJDQU5fUkVUT1VSX1RSQU5TQUNUSU9OXCI6XCIxXCIsXCJDQU5fQ0FOQ0VMX1ZFTlRFXCI6XCIxXCIsXCJDQU5fQ0FOQ0VMX0JMXCI6XCIxXCIsXCJDQU5fQ0FOQ0VMX1RSQU5TQUNUSU9OXCI6XCIxXCIsXCJTSE9XRlNcIjpcIjBcIixcIlNob3dCTFwiOlwiMVwiLFwiU2VuZENvbW1hbmRlRm91cm5pc3NldXJcIjpcIjFcIixcIkNhbkRvUmV0b3VyRm91cm5pc3NldXJcIjpcIjBcIixcIk9ubHlMaW1pdGVGYWN0VG9JUE1cIjpcIjBcIixcIk9ubHlMaW1pdGVGYWN0VG9CUFwiOlwiMFwiLFwiQ2FuQ2hhbmdlUHJpeFZlbnRlXCI6XCIxXCIsXCJTaWduYXR1cmVcIjpcIlwiLFwiUlNcIjpcIjBcIixcIklkRW1wbG95ZVwiOlwiMTEwXCJ9IiwiaXNzIjoiaHR0cHM6XC9cL2dyb3VwZS1wYW0ubmV0IiwiYXVkIjoiaHR0cHM6XC9cL2dyb3VwZS1wYW0ubmV0IiwiaWF0IjoxNjY0NzMzNjAwLCJuYmYiOjE2NjQ3MzM2MDAsImV4cCI6MTY2NDgyMDAwMH0.ytB5omXmtnpO4iQVCyePZPXtNoiQ4Uh4C_4Ibs70Iag'


  };

  /*
  * For easier debugging in development mode, you can import the following file
  * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
  *
  * This import should be commented out in production mode because it will have a negative impact
  * on performance if an error is thrown.
  */
   import 'zone.js/dist/zone-error';  // Included with Angular CLI.

