/* eslint-disable max-len */
// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  userName: '',
  passWord: '',
  endPoint:'http://technopharm.homeip.net/nabysyrhrs/',
  // tokenUser:''
  tokenUser:'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYW1fYXBwbGljYXRpb24iOiJbTkFieVN5IFJIIC0gUlNdIiwicGFtX2NsaWVudCI6Ii1QQVVMIEVUIEFJQ0hBIE1BQ0hJTkVSSUUtIiwiY2xpZW50X2FkciI6IlphY2sgTWJhbyBEQUtBUlwvU0VORUdBTCIsImNsaWVudF90ZWwiOiJUZWw6ICsyMjEgMzMgODM2IDE0IDc3IiwiYm91dGlxdWVfaWQiOjAsInVzZXJfaWQiOjMsInVzZXJfbG9naW4iOiJ0aGllcm5vIiwidXNlcl9kYXRhIjoie1wiSURcIjpcIjNcIixcIk5PTVwiOlwiVEhJRVJOT1wiLFwiUFJFTk9NXCI6XCJBQkRPVUxBWUVcIixcIkFEUkVTU0VcIjpcIlwiLFwiVEVMXCI6XCJcIixcIkxPR0lOXCI6XCJ0aGllcm5vXCIsXCJQQVNTV09SRFwiOlwiODFkYzliZGI1MmQwNGRjMjAwMzZkYmQ4MzEzZWQwNTVcIixcIkRBVEVFTlRSRUVcIjpcIlwiLFwiREFURUNSRUFUSU9OXCI6XCJcIixcIkhFVVJFQ1JFQVRJT05cIjpcIlwiLFwiTklWRUFVQUNDRVNcIjpcIjRcIixcIlBST0ZJTEVcIjpcIkFEP0lOSVNUUkFURVVSXCIsXCJCTE9RVUVcIjpcIk5PTlwiLFwiTG9jYWxMb2dpbkNvZGVcIjpcIjBcIixcIkNIQU5HRURBVEVcIjpcIjBcIixcIkNIQU5HRUZBQ1RVUkVcIjpcIjBcIixcIkNIQU5HRVRPVEFMQk9OXCI6XCIwXCIsXCJTSE9XSU5WRU5UQUlURV9BVlwiOlwiMFwiLFwiU0hPV0ZBQ1RVUkVcIjpcIjBcIixcIlVQREFURVBBU1NXT1JEXCI6XCIwXCIsXCJVUERBVEVTVE9DS1wiOlwiMFwiLFwiQ0hBTkdFTElWUkFJU09OREFURVwiOlwiMFwiLFwiRVRBVFwiOlwiQWN0aWZcIixcIlNIT1dDQUlTU0VcIjpcIjBcIixcIlNIT1dNQUdBWklOXCI6XCIwXCIsXCJPbmx5TGltaXRlRmFjdFRvRGF5XCI6XCIwXCIsXCJTaG93U3RvY2tWZW50ZVwiOlwiMFwiLFwiU0hPV01hZ2FzaW5cIjpcIjBcIixcIkNBTl9SRVRPVVJfVkVOVEVcIjpcIjFcIixcIkNBTl9SRVRPVVJfQkxcIjpcIjFcIixcIkNBTl9SRVRPVVJfVFJBTlNBQ1RJT05cIjpcIjFcIixcIkNBTl9DQU5DRUxfVkVOVEVcIjpcIjFcIixcIkNBTl9DQU5DRUxfQkxcIjpcIjFcIixcIkNBTl9DQU5DRUxfVFJBTlNBQ1RJT05cIjpcIjFcIixcIlNIT1dGU1wiOlwiMFwiLFwiU2hvd0JMXCI6XCIxXCIsXCJTZW5kQ29tbWFuZGVGb3Vybmlzc2V1clwiOlwiMVwiLFwiQ2FuRG9SZXRvdXJGb3Vybmlzc2V1clwiOlwiMFwiLFwiT25seUxpbWl0ZUZhY3RUb0lQTVwiOlwiMFwiLFwiT25seUxpbWl0ZUZhY3RUb0JQXCI6XCIwXCIsXCJDYW5DaGFuZ2VQcml4VmVudGVcIjpcIjFcIixcIlNpZ25hdHVyZVwiOlwiXCIsXCJSU1wiOlwiXCIsXCJJZEVtcGxveWVcIjpcIjExMFwifSIsImlzcyI6Imh0dHBzOlwvXC9ncm91cGUtcGFtLm5ldCIsImF1ZCI6Imh0dHBzOlwvXC9ncm91cGUtcGFtLm5ldCIsImlhdCI6MTY2MTYzOTkyNywibmJmIjoxNjYxNjM5OTI3LCJleHAiOjE2NjE3MjYzMjd9.9DfwpzCOLDphUNAgjmL1QlPqhj_ZaxykAUC2DtxpL8E'

  };

  /*
  * For easier debugging in development mode, you can import the following file
  * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
  *
  * This import should be commented out in production mode because it will have a negative impact
  * on performance if an error is thrown.
  */
  // import 'zone.js/dist/zone-error';  // Included with Angular CLI.

